version : 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      -mvn clean install
  post-build:
    commands:
      -echo build completed
  artifacts:
    files:
      -target/*.war
      -scripts/*.sh
      -appspec.yml
    discard-paths: yes
